[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug" ]

chain_spec_path = "configs/paseo-local.json"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9945

[[parachains]]
id = 1000
chain_spec_path = "configs/asset-hub-paseo-local.json"

[[parachains.collators]]
name = "collator-01"
command = "./bin/polkadot-parachain"
args = [ "-lparachain=debug" ]
rpc_port = 9988
