#!/usr/bin/env bash
# Ensure committed .github/media/ assets match what the generator produces.
# Catches hand-edits and out-of-sync regenerations.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
TMP="$(mktemp -d)/media"
TMP_DOCS="$(mktemp -d)/docs"
mkdir -p "$TMP" "$TMP_DOCS"

# Run the generator pointing at tmp dirs by swapping env.
# generate.py reads paths from git rev-parse, so we temporarily redirect by
# patching its output root via an env var contract: honor $BRAND_OUT_MEDIA /
# $BRAND_OUT_DOCS if set (generator already supports --dry-run, simpler).
python3 "$REPO_ROOT/.claude/skills/branding/generate.py" --dry-run > /tmp/brand-drift.log

# The generator in --dry-run mode writes to an ephemeral temp dir and prints
# the path on the first line ("▸ dry-run → …"). Diff that against the real
# committed assets.
DRY_DIR=$(grep -oE 'dry-run → [^ ]+' /tmp/brand-drift.log | head -1 | awk '{print $3}')
if [[ -z "$DRY_DIR" || ! -d "$DRY_DIR" ]]; then
  echo "✗ could not locate dry-run output dir"
  exit 2
fi

diff_out=$(diff -r "$REPO_ROOT/.github/media" "$DRY_DIR" 2>&1 || true)
# Filter: ignore anything not generated by /branding (icons, dot-logo-*, coverage.svg, BRANDING.md)
filtered=$(printf '%s\n' "$diff_out" | grep -vE '(icons|dot-logo-|coverage\.svg|BRANDING\.md|CHANGELOG\.md|\.gitkeep)' || true)

if [[ -n "$filtered" ]]; then
  echo "✗ drift detected between templates and committed assets:"
  echo "$filtered" | head -60
  echo ""
  echo "Fix: bash .claude/skills/branding/generate.sh && git add .github/media"
  exit 3
fi
echo "✓ no drift — generated assets match templates"
